name: "Docfx Action"
author: "PhantasmicDev"
description: ""
branding:
  icon: "file-text"
  color: "white"

inputs:
  my-input:
    description: "Input Example"
    required: false

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
